### ISSUE TITLE
Read GitHub Discussions page

### ISSUE THREAD

**Issue by KCollins007** [Studio-Ops-Org/Studio-2022-S1-Repo#2]
Read GitHub Discussions page Team Policies & Best Practice documentation

- [x] Kristen Collins
- [x] Cassidy McCosh
- [x] Mathew Nichols
- [x] Sam Winton
- [x] Zac Pepper
- [x] Frederic Cui
- [x] Conor West
- [x] Hayden McDowall

**Comment by westcl4** [comment]
Am I stupid? There does not seem to be any content in the discussions tab!

**Comment by mccoc12** [comment]
@westcl4 Sorry, it can be a tad bit confusing! The discussions page we are referring to is the team's discussion page not the organisation's discussion page. Here's a [link](https://github.com/orgs/Studio-Ops-Org/teams/2022-s1) for you. If you open up our GitHub from your homepage it should default to this discussion page. If you're still having trouble on Thursday I can show you where to find it.
