### ISSUE TITLE
Set up 21 VM in Azure

### ISSUE THREAD

**Issue by KCollins007** [Studio-Ops-Org/Studio-2022-S1-Repo#21]
21 Linux VM set up in Azure. Standard B1ls (1 vcpu, 0.5 GiB memory). Two users per machine. bitstudent and manager with sudo access.

On campus access only

Faisal to set up resource group

**Comment by mccoc12** [comment]
VMs handed over. Usernames and passwords for the accounts are held in a KeePass file inside Teams (General > Projects > Miscellaneous).
