### ISSUE TITLE
Install Puppet on Ubuntu 20.04

### ISSUE THREAD

**Issue by s-winton** [Studio-Ops-Org/Studio-2022-S1-Repo#26]
OE2 labs use ubuntu 18.04, Faisal wants to upgrade to the latest version 20.04. Compatibility issues on 20.04 may lead to change in lab instructions. Install and test puppet on ubuntu 20.04, fix compatibility issues and update the lab instructions

**Comment by eadsysadmin** [comment]
FYI Ubuntu 20.04 is stable in Azure. This is the version employed by the DB2 and DB3 teaching servers.
