### ISSUE TITLE
Database Specs

### ISSUE THREAD

**Issue by mccoc12** [Studio-Ops-Org/Studio-2022-S1-Repo#33]
Collate the data from the DB2 security machine, the DB2 mariadb, and the DB3 docker server to be able to recreate. Write a small report with the following:
- [x] ports open/mapped
- [x] software versions
- [x] vhardware 
- [x] NSG configuration

The purpose of this is to be able to create new development machines from this report.

To be done before class on Thursday the 17th. and uploaded to teams under **General > Projects > Azure DB2 Server** AND **General > Projects > Azure DB3 Server**

**Comment by westcl4** [comment]
These resources are in the BIT_db_project resource group on Azure.
