### ISSUE TITLE
Set up KeePass

### ISSUE THREAD

**Issue by KCollins007** [Studio-Ops-Org/Studio-2022-S1-Repo#4]
Set up KeePass using document [Using KeePass](https://teams.microsoft.com/_#/docx/viewer/teams/https:~2F~2Fotagopoly.sharepoint.com~2Fsites~2FStudioOpsTeam~2FShared%20Documents~2FGeneral~2FKeys~2FUsing%20KeePass.docx?threadId=19:AdunKoJnmCx3P1R4tSL8O0joeBie0LC74xgU58L94tU1@thread.tacv2&baseUrl=https:~2F~2Fotagopoly.sharepoint.com~2Fsites~2FStudioOpsTeam&fileId=c0bbcdc0-eb5c-4aa4-8527-1da3d7eb7555&ctx=files&rootContext=items_view&viewerAction=view) in Teams

- [x] Kristen Collins
- [x] Cassidy McCosh
- [x] Mathew Nichols
- [x] Sam Winton
- [x] Zac Pepper
- [x] Frederic Cui
- [x] Conor West
- [x] Hayden McDowall

**Comment by westcl4** [comment]
To do: Get password for myself from the team!
