### ISSUE TITLE
Set up a work log

### ISSUE THREAD

**Issue by KCollins007** [Studio-Ops-Org/Studio-2022-S1-Repo#5]
Set up a way to record weekly tasks, evidence gathered and documentation (OneNote, Word or Other)

- [x] Kristen Collins
- [x] Cassidy McCosh
- [x] Mathew Nichols
- [x] Sam Winton
- [x] Zac Pepper
- [x] Frederic Cui
- [x] Conor West
- [x] Hayden McDowall

**Comment by westcl4** [comment]
How flexible is this? Is this up to our own discretion?
