### ISSUE TITLE
Snapshot Documentation

### ISSUE THREAD

**Issue by mccoc12** [Studio-Ops-Org/Studio-2022-S1-Repo#75]
Create documentation around the process of snapshotting a machine, creating a disk, and deploying a new machine. Include screenshots where applicable and use our Azure conventions for tagging. 
- [x] Creating a snapshot 
- [x] Creating a disk from the snapshot
- [x] Deploying a new VM from the disk
- [x] Swapping the disk on an already created VM

Upload to **General > Projects > Miscellaneous** before class on Thursday the 14th of April.

**Comment by s-winton** [comment]
Documentation can be found on [teams:](https://otagopoly.sharepoint.com/:w:/s/StudioOpsTeam/EWV8tIYd0P9CvCuoF4uGIGIByHF_XadG8ihGNPiBO58Amw?e=eWdev3)
