### ISSUE TITLE
Documentation of Ticketing System

### ISSUE THREAD

**Issue by mccoc12** [Studio-Ops-Org/Studio-2022-S1-Repo#89]
Create a document that explains how the RT system was created, the specific configuration that is needed, how to maintain it, and how to use it.

**Comment by s-winton** [comment]
Found in [teams](https://otagopoly.sharepoint.com/:w:/s/StudioOpsTeam/Ea8hbTCLZ4dOvj5-rfc8DSsBG73Is1VKjftPXeGNCHiHOA?e=PaQYwg) under Projects > Miscellaneous > RT5
